### ISSUE TITLE
[Feature request] PGA

### ISSUE THREAD

**Issue by eiso** [src-d/datasets#30]
```
pga get --siva 00035a4b79ce6b9a4cd7e7006bd78aa153cb9389.siva
```

Rationale: when debugging I realized I wanted to download several specific siva files locally to understand what was going on with them.

**Comment by eiso** [comment]
```
~/temp master 
: echo "00035a4b79ce6b9a4cd7e7006bd78aa153cb9389.siva" | pga get -i
downloading siva files by name from stdin
filter flags will be ignored
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/src-d/datasets/PublicGitArchive/pga/cmd.downloadFilenames(0xa39da0, 0xc420040d90, 0xa39e00, 0xc420040da0, 0xc4200e0420, 0x2, 0x2, 0xa, 0x8000107, 0x0)
	/home/mthek/go/src/github.com/src-d/datasets/PublicGitArchive/pga/cmd/get.go:91 +0x273
github.com/src-d/datasets/PublicGitArchive/pga/cmd.glob..func1(0xa6cf00, 0xc420040d60, 0x0, 0x1, 0x0, 0x0)
	/home/mthek/go/src/github.com/src-d/datasets/PublicGitArchive/pga/cmd/get.go:79 +0x3e8
github.com/src-d/datasets/PublicGitArchive/pga/vendor/github.com/spf13/cobra.(*Command).execute(0xa6cf00, 0xc420040d50, 0x1, 0x1, 0xa6cf00, 0xc420040d50)
	/home/mthek/go/src/github.com/src-d/datasets/PublicGitArchive/pga/vendor/github.com/spf13/cobra/command.go:698 +0x47a
github.com/src-d/datasets/PublicGitArchive/pga/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa6d340, 0xc42004ff50, 0x74de55, 0xc4201063c0)
	/home/mthek/go/src/github.com/src-d/datasets/PublicGitArchive/pga/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/src-d/datasets/PublicGitArchive/pga/vendor/github.com/spf13/cobra.(*Command).Execute(0xa6d340, 0x0, 0x0)
	/home/mthek/go/src/github.com/src-d/datasets/PublicGitArchive/pga/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/src-d/datasets/PublicGitArchive/pga/cmd.Execute()
	/home/mthek/go/src/github.com/src-d/datasets/PublicGitArchive/pga/cmd/root.go:34 +0x31
main.main()
	/home/mthek/go/src/github.com/src-d/datasets/PublicGitArchive/pga/main.go:8 +0x20
```

**Comment by campoy** [comment]
You can currently do `echo 00035a4b79ce6b9a4cd7e7006bd78aa153cb9389.siva | pga get -i`

Is that enough? I just sent a PR fixing the issue you encountered, btw

https://github.com/src-d/datasets/pull/31
